services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-storage-api
    env_file:
      - .env
    ports:
      - "80:8080"
      - "8080:8080"
    volumes:
      - file_data:/app/files
    restart: unless-stopped

volumes:
  file_data:
